# Site settings
title: Azureish Live!
description: A fortnightly live show on Azure
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Azureish Live!
user_description: A live show where our hosts build something in Azure in 1 hour. Every other Tuesday.
user_title: A live show where our hosts build something in Azure in 1 hour. Every other Tuesday.
email: contact@azureishlive.com
twitter_username: AzureishLive
github_username:  AzureishLive

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
